		var table = [

			10,1,"symbol",
			11,2,"there exist symbols",
			12,3,"there exist symbols and only symbols",
			13,4,"symbols are referred to in lots of different ways. They are still symbols.",
			14,5,"symbols always represent.",
			15,6,"symbols do not exist alone.",
			16,7,"the universe exists in totality.",
			17,8,"the universe is symbolic.",
			18,9,"the universe is all symbols in all relations.",
			19,10,"time is symbolic.",
			20,11,"space is symbolic",
			21,12,"all dimensions of reference are symbolic",
			22,13,"measurement is symbolic",
			23,14,"perception is measurement is symbolic. symbolic systems measuring symbolic systems.",
			24,15,"Existence in totality is the sum of all symbols and their symbolic relations.",
			25,16,"Symbols are in relations",
			27,17,"how things relate is the thing.",
			28,18,"relations can only be measured symbolically",
			28.1,19,"The issue is we actually live. We see and taste and absorb and feel. It confounds and confuses. It makes us fuck and hug and puke and drink and cry. And sometimes right and write. SIGH.",
			29,20,"measurement is a symbolic transcoding. a symbol impresses into other symbols and their relations.",
			30,21,"symbols related are networks",
			31,22,"the atomic aspect of a network is empty",
			32,23,"empty or nothing is symbolic",
			33,24,"from nothing comes something",
			34,25,"if anything exists at all, *all of it* must exist. all of it equals all things and their relations",
			35,26,"Laws of nature are metaphors->temporary, localized reductions of symbols. The laws exist but do not accurately describe existence.",
			36,27,"All things exist implies all laws, even the absurd, exist",
			37,28,"Logically inconsistent or false laws or non-sense exist but are not robust.",
			38,29,"Robust is a property of symbols and relations that are more numerous and more probable in more networks",
			39,30,"Extremely robust networks are labeled laws. Laws are not true and are not false. They are just symbols and relation.",
			40,31,"There is only one law: everything in relation.",
			41,32,"It is not possible to reduce everything in relation beyond its total symbolic relations.",
			41.1,33,"INTERJECTION: Master of body in relationship with an environment is the highest form of human enlightenment. The syncopation of a loosely coupled network tuning into the environmental network produces and induces in others a perspective awe. Commanding a large scale coordinated flow is improbable.",
			41.2,34,"A total symbolic relational exposition would include all implied states and all assumption and all initial conditions",
			42,35,"Probability is symbolic",
			43,36,"Probability is the symbol in partial contingent relation to other symbols. it is also a symbol of unknown.",
			44,37,"Randomness is symbolic",
			45,38,"Random is the symbol non-contingent relations.",
			46,39,"All is infinite",
			47,40,"Infinite is the totality of all symbols and their relations",
			48,41,"Symbols are in relations. Relations are symbolic. Relations are symbols of magnitude, direction, scope, size, sum, transposition, composition, arithmetic, concepts and so on.",
			49,42,"Symbols exist in totality. Symbols are discovered not created.",
			50,43,"Symbols are discovered by other symbols and/or symbolic networks.",
			51,44,"Discovery is a symbol. It is symbols in relation.",
			52,45,"Symbols persist through relation.",
			52.1,46,"The symbols in relation are composite symbols.",
			53,47,"Infinity is a symbol. A symbol in relation. And a composite symbol.",
			54,48,"Symbols in relation may be a priori and a posteri in relation.",
			55,49,"The only activity in the universe is replacement.",
			56,50,"All relations are replacements. Symbols replacing symbols.",
			57,51,"That which can be replaced is not a unique symbol.",
			58,52,"Replaceable and not replaceable symbols are the only two distinctions.",
			59,53,"Non-replaceable symbols are atomic. The set of non-replaceable symbols is infinite in quantity.",
			60,54,"The set of replaceable symbols is infinite.",
			61,55,"Set of replaceable symbols > set of non-replaceable. By the proof: Set of replaceable symbols includes set of non-replaceable symbols because non-replaceables are replaceable by themselves.",
			62,56,"IS creates",
			63,57,"IS is the the symbol and relations common origin.",
			64,58,"IS is One",
			65,59,"IS is One multiples",
			66,60,"IS splits One into ones",
			67,61,"IS disa-symbols",
			68,62,"Truth Is",
			69,63,"Truth Is. False Is Not.",
			70,64,"Truth is a symbol.",
			71,65,"Truth forbids any deconstruction",
			72,66,"True symbolic relations are not Truth.",
			73,67,"Truth is the entire set of all symbols and their relations. True symbolic relations and false symbolic relations and undecided symbolic relations.",
			74,68,"true is a statement of equivalency.",
			75,69,"This symbol is. This symbol is that symbol. These are truth statements. This is logic. In all its forms.",
			76,70,"Whether a logic is true is contained within its network symbolic locality.",
			77,71,"The whole of existence being all symbols and their relations logically true symbolic statements of relation are merely a subnetwork of relations. So symbolically contained as to be consistent, close and have other such qualities.",
			78,72,"True is consistency.",
			79,73,"Consistency is symbolic relation from here to there. Can you trace the path of relations from one symbol to another?",
			80,74,"Consistent Consistency is Robust. Robust is symbolic relatability across many relational paths.",
			81,75,"True is robust. True is more true the more relational paths connect same symbols.",
			82,76,"Truth is the totality of true(s). Truth is infinite robustness and the connection of all to all.",
			83,77,"True is symbolic relations including false ones that are provably false and provably false. False symbolic relations are not robust.",
			84,78,"Provability. Proof is symbolic relations. Proof is a compound series of symbolic relations_relating a symbolic relation to a symbolic relation, true.",
			85,79,"Reality is a symbolic subnetwork with a central node perspective.",
			86,80,"Reality is the relations within reach of a partial symbolic node.",
			87,81,"In order to communicate symbols and relations must be composed and their full symbolic fidelity reduced. The network of relations cannot propagate full symbolics at all levels/between all nodes and subnetworks of relations.",
			88,82,"Symbolic relations emerge at higher levels of composition.",
			89,83,"Symbolic relations loop or re-emerge at all levels of composition.",
			90,84,"the One and the infinite and the multiple hold relation at all levels of composition.",
			91,85,"Re-emergent symbolic relations are robust. True symbolic relations will be abstraction or composition independent. Or the composition is reducible to the fundamental symbols.",
			92,86,"Categories, labels, taxonomies and ontologies are reductive, coarse symbolics of symbolics.",
			93,87,"Commonly human defined categories are more or less robust depending on withstanding scrutiny and use",
			94,88,"A sign of robustness is survivability under varied and large quantity use.",
			95,89,"Identity as an objectification of symbols and relations into a labeled composition - a category - is a robust symbol.",
			96,90,"To Identify is to relate.",
			97,91,"To Identify is not possible between symbolic compositions and decompositions except for the most robust, fundamental symbols: one, infinity, zero",
			98,92,"To Identify is to separate. To Make Difference. To Decide Same.",
			99,93,"The separation is the act of IS. Identification IS the act of Same and Difference. If not equivalent, then different.",
			100,94,"There is One and Multiple.",
			101,95,"There is Multiple of Multiples - the infinity.",
			102,96,"There is cycle. A circle. The Infinity of Infinities.",
			103,97,"And yet it has number. PI. or does it. PI is infinite and finite. It lives in between. or does it. That is symbolic and relations... it is both.",
			103.1,98,"INTERLUDE X. don't know.",
			104,99,"Previous (t) was an example. Examples and variables are stand in symbols. They take on the symbolic relations of their imposters or reductive neighbors.",
			105,100,"Metaphors, analogies, similes, cliches, recognized patterns are sometimes examples or variables. Symbolic systems/symbolic relations.",
			106,101,"All a composite.",
			107,102,"Relation is a symbol.",
			108,103,"Symbol is not. Symbol is meta-existent. Symbol is Symbolic.",
			109,104,"One, multiple, zero, infinite composed into symbols and relations_symbols towards symbols.",
			1010,105,"This Explains No Thing.",
			110,106,"Explanation is the relation of true compositions - more less robust.",
			111,107,"This Generates.",
			112,108,"Nothing is Explainable. Symbols are composed-generated.",
			113,109,"Symbols generate symbols.",
			114,110,"A single bit flip. From 0 to 1. 0 from 1. 0 /= 1. 0 not 1. 0,1. Generates All.",
			115,111,"Binary. Generate.",
			116,112,"Composition of symbols -> symbols is merely binary expansion.",
			117,113,"the space of all binary strings is. All is the space of all binary strings.",
			118,114,"What can we express?",
			119,115,"Everything. What cannot be express as a finite binary string... is just an infinite binary string.",
			1110,116,"Infinities have countable, thus, symbolic representations. If one needs proof. Infinity as a reductive symbol is more or less robust.",
			120,117,"Genetics is expressible as binary strings.",
			121,118,"Genetic symbolics are symbolic relations that re-encode_replicate.",
			123,120,"Self replicating",
			123.1,121,"INTERLUDE: Roads.",
			123.2,122,"PG: interlude.",
			124,123,"Self. is. identity. 1=1. the one.",
			125,124,"Other than the One, without relations other than to the Zero or the Multiple, all self(s) are symbols of symbols considered in some relations as isomorphic, equivalent to the One. A person is a self but only when related without regard to a person's biology or history. A person is the One in the context of A Collection of Persons, the pure Multiple of the abstract person(s). Any deeper, richer, more relatable description of a person or the collection of persons decomposes and exposes the myth of the One.",
			126,125,"Self and the One have only the slightest of existence. In relation to itself and not itself. the relation is *is* and *is not* - not *similar* or composed or bigger or almost.",
			127,126,"This manuscript of thoughts (ts) relates to nothing true. It relates the writer to the reader in an infinite network. If it is not read it relates the writer to the writer. The pen and ink have been decomposed. The paper and ink have relation. But the ideas represented by the orderly ink, if not read, only re-relate the writer to his series-persons.",
			128,127,"From the spiraling relations emerges new symbols and relations. In relation of relation only... the recurrence of relations is symbol. Networks are symbol are relations -> relations. f(relations)=relation.",
			129,128,"The idea of emergence, of symbolic creation, is absurd. There exist two relations IS and IS NOT. Count was in the running but count itself is an IS.",
			130,129,"IS NOT. Negation. Falsification. That is the Only Relation. IS NOT is the differentiation.",
			131,130,"Everything is.",
			132,131,"You are everything.",
			133,132,"You are the center of Everything.",
			134,133,"You are.",
			134,134,"I am.",
			135,135,"I am everything.",
			136,136,"At the center, everything exists.",
			137,137,"From you and I everything and everything coincides.",
			138,138,"The multiple of you and I is the coincidence of everything's multiple.",
			140,139,"It is broken.",
			14-1,140,"The multiplicity of everything is reductive. You and I are reductive.",
			141,141,"From bits... 1 and 0... everything can be encoded. Infinity, infinite messages, infinite structure, infinite identities.",
			142,142,"Encoding is at issue.",
			143,143,"What is encoding? what does the encoding? What is encoding without decoding?",
			144,144,"It cannot be.",
			145,145,"Its encoding other its.",
			146,146,"What. Does. This. Work.",
			147,147,"The speed of light is only finite from the perspective of the outside observer, from the perspective of a photon, it's infinite. Time ceases to exist for a photon.",
			148,148,"The speed of gravity is the same as the speed of light. All *fields* share this speed.",
			149,149,"It is irrelevant what the speed is, it's that it is at all. (speed is a relative measure anyway.)",
			150,150,"A limit to information creation, encoding, decoding-> that IS what does the work. Physics fields and photons are no less and no more than differentiators. The pure difference.",
			151,151,"No Limit must twin with LIMIT.",
			152,152,"If Everything is No Limits, Limits are contained within. ?",
			153,153,"Limits thus cause *it from bit*",
			154,154,"That information (difference, One vs. Multiplicity) is Limited is the condensation gesture.",
			155,155,"Information slowed becomes mass and matter.",
			156,156,"The entire spectrum of limits is contained within Everything.",
			157,157,"That information slows is it. the effects of information transcoding is the different engine.",
			158,158,"The entire whole of number theory will be shown to be all the effects of slowed info.",
			159,159,"A photon. A bit. Spin, mass, charge, wave, particle. Bits composed describe and through description (definition, differentiation) all the properties/laws/behaviors/itness of a photon. Photons we continue to discover new things about. All discovery uses photons uses bits composed uses bits to uncover more of that that does the uncovering.",
			160,160,"Photons do not provide mass. Mass is defined as the energy and momentum of an *object* or system of objects... which is a relation between energy and speed of a field. Photons have no mass because speed from the frame of reference of a photon does not exist_time does not exist for a photon... (nor a bit).",
			161,161,"Perhaps Mass comes from Higgs mechanism_symmetry breaking... differentiation. Perhaps gauge fields... symmetry breaking...",
			162,162,"A great deal of symbolic logic is deployed to describe the composition of fields, particles, systems and their properties and relations. All of which - the *accuracy* of the logical composition, The Math, rides on CONSTANTS... quantities... strings of numbers... bits and bits",
			163,163,"To achieve perfect definition - a complete model_would be to achieve the creation of the system modeled.",
			164,164,"A complete model of the universe requires the complete symbolic composition - all bits in relation to each other. Even the reductive compositions - those subsystems describable by formulas e.g. the even counting numbers - require the formula and proof that it is reductive.",
			165,165,"THE MATH is not outside THE WHOLE.",
			166,166,"THE MATH is not the thing. Math and mathematical models and descriptions are things unto themselves.",
			167,167,"Engineering based on math is a thing, different than math used to initiate its composition.",
			168,168,"A complete recipe for proteins or protein sequences is the sequence itself. A mathematical models/description is a different thing.",
			169,169,"Synthetic proteins and other synthetic systems are not the systems they resemble.",
			170,170,"The physics and chemistry unveils as it does in infinite complexity because there is no other way for everything to be.",
			171,171,"From the constants and relations between symbols one uncovers a model for a universe... the universe of universes allows for all possible universes.",
			172,172,"Proof is not possible.",
			173,173,"Proof of a claim is not outside the whole.",
			174,174,"Proof does not validate existence.",
			175,175,"Proof must be proved?",
			176,176,"Proof is a symbolic thing unto itself.",
			177,177,"The Math and The Physics is a symbolic relation. Not The Symbolic Relation.",
			178,178,"The universe does not do math not obey physics. The universe does not compute nor is it a computer. It does not philosophize not create nor understand.",
			179,179,"It is not beautiful nor ugly nor signifying nor sign nor representative.",
			180,180,"There are symbols and relations. Symbols are not the stand-ins of human symbolics. Symbols are atomic its. Pure existence. IS and IS Not.",
			181,181,"Symbols Can Represent.",
			182,182,"Symbols Can Represent through relation.",
			183,183,"There is no case for cause.",
			184,184,"Cause is a tragically-fatal reduction.",
			185,185,"Cause is a partial relation.",
			186,186,"Cause, if true, would require a source and object.",
			187,187,"nothing causes 1+1=2.",
			188,188,"1+1 IS 2. That is the end.",
			189,189,"The 4 forces of physics do not cause existence nor reality.",
			190,190,"Random is not caused.",
			200,191,"The cause of randomness IS.",
			201,192,"The cause of order IS NOT.",
			191,193,"A table IS a table only symbolically. Through its relation to chairs and people.",
			192,194,"Symbols are symbols through relation only. A symbol does not stand alone... does not exist alone.",
			193,195,"This is not a language game.",
			194,196,"Language is just symbols relating. Representations of relations as well as relations itself.",
			195,197,"Language does not have a cause. It is pure effect.",
			196,198,"There is no singular cause other than IS. Differentiation IS the only cause. EVery relation is effectual.",
			197,199,"Cause, in the common notion, is a symbols of effects.",
			198,200,"Directly: physicality IS information through the medium of time.",
			199,201,"Time is a medium of information. Time is pure differentiation. Time is states of information.",
			202,202,"Thermodynamic laws are such...arrow of time implicated by probability of states of information...",
			203,203,"Doing proper science requires mathematical proof as well as falsification experiments of these claims.",
			204,204,"To falsify a valid/plausible/possible alternative conception of reality must be supplied.",
			205,205,"All alternate concepts of time, space and information are absurdly reified. Those reified concepts such as ether, fields, etc are no more falsifiable than the reality depicted in previous (ts) stated herein.",
			206,206,"This is the fundamental reality of reality.",
			207,207,"Symbols upon symbols. Experiments validating math, validating narratives validating experiments.",
			208,208,"No scientific nor religious nor mathematical or philosophic theory or model of the world has been validated as true, absolutely.",
			209,209,"Evolution, The Standard Model, Quantum Mechanics, N/=NP, and so on are all incomplete. Provably so. Depending on definition of proof.",
			210,210,"Science is agreed to be sufficient only utility. Is it useful?",
			211,211,"A theory or model is useful if it connects symbolic systems - typically in a reductive/computable way.",
			212,212,"That is, a scientific theory must be understandable and implementable within a system to be exploited as a model.",
			213,213,"The more a system needs to embody the more science it encodes.",
			214,214,"The science is not true. It is merely a useful symbolics with enough robustness to connect symbolic networks.",
			215,215,"Utility is relative to the systems in which the thing being used is being used.",
			216,216,"Utility is not a fundamental property (relation). It is the symbolic relation compounded from exchanges.",
			217,217,"Exchanges are Pure information relations. SYmbolic representation of energy, mass, momentum, force, currency, social ties.",
			218,218,"Value is a symbolic compound making exchange computable.",
			219,219,"Value reduces information in an exchange.",
			220,220,"GDP and other macroeconomic symbolics increase over time because instantaneous / all information is conserved. That is, value exchange reduces information in Exchange so more value must be exchanged over time.",
			221,221,"Everything is a network. Everything is connected. Changes to the network are information through time.",
			222,222,"Improbable relations are non-robust subnetworks.",
			223,223,"Improbability is higher fidelity relations... contains more information...information as subnetworks moving quickly through time.",
			224,224,"Improbably events->less robust relations->symbolically rich->indeterminate relations->compounds of compounds->random is TOTAL IMPROBABILITY.",
			225,225,"Value accumulates quickly to the improbable.",
			226,226,"Value dissipates from the improbable quickly.",
			227,227,"Value tends to the probable.",
			228,228,"The probable is always more probable.",
			229,229,"The improbable is always possible and neither more improbable.",
			230,230,"Probable, being symbolically robust, is reducible -> computable -> predictable -> valuable -> price-able.",
			231,231,"Improbable is anti-value. It is not computably -> reducible -> predictable -> price-able.",
			232,232,"There is no cause to probable or improbable relations. They are symbols of the underlying relational complexity. There is no *force* *causing* complexity, probability, quantum...",
			233,233,"It is fully explainable in terms of symbols and relations... symbolic relations...pure relation. It is physics, animal behavior, economics... those are mere descriptions...reduced symbols relating IN DESCRIPTION symbols to other symbols.",
			234,234,"Explainability is only a requirement within the symbolic logic system of science. The universe / existence is trans-explanation. It is not fundamental. In fact, the improbable and non-computable and the infinite and the transcendental indicate non-explanation is fundamental.",
			235,235,"Explanations are not TRUE nor The Truth.",
			236,236,"Therefore explanations cannot cause relations. [This is the assumption underlying modernity] Ideologies, Beliefs, Programs do not cause anything. These are symbols applied/related to reductive explanatory systems.",
			237,237,"Animals are in relation. Atoms are in relation. Planets are in relation. Humans are in relation. ...",
			238,238,"These are in relation.",
			239,239,"The demarcation is the relational act. The demarcation is The Event. This from that. These from those.",
			240,240,"We demarcate.",
			241,241,"I demarcate therefore I am.",
			242,242,"Therefore demarcates effect.",
			243,243,"I demarcate. Iam.",
			244,244,"I am in relation.",
			245,245,"I do not cause relation.",
			246,246,"I am.",
			247,247,"I relates to not I.",
			248,248,"I is infinitely related to not I.",
			249,249,"I am not I.",
			250,250,"a relational recursion.",
			251,251,"I cannot self-demarcate.",
			252,252,"I must be in relation to not I. Not I can demarcate.",
			253,253,"1 is 1 only in relation to not 1. 1 does not declare 1 is 1. Not 1 declares *not 1* is not 1. *1* is *not 1* is not a relation. If two symbols declare the other themselves they are the same, but they cannot self-declare.",
			254,254,"A single bit a 1 or a 0, alone, cannot compute.",
			255,255,"A point is zero-dimensional.",
			256,256,"A point cannot, does not, exist by itself.",
			257,257,"A point is coordinated.",
			258,258,"None of this is solipsism. It is all beyond solipsism. If the self cannot self demarcate solipsism is not fundamental.",
			259,259,"The universe / infinite does not declare itself. It is.",
			260,260,"What utility is there in this account of reality? Transcription -> connection -> transcoding -> imagination.",
			261,261,"Light is misinterpreted -> mis-assigned as a thing one sees. Light is information through time. A photon has frequency. It has information. But only in relation. A photon does not self-declare.",
			262,262,"A bit has no frequency. It has no physicality. It cannot self-declare. A bit is fundamental.",
			263,263,"Photons emit as a result of electrons changing orbits. Or-bits. Photons are symbolic compositions of bits. Charge, spin, Orbit... composition of bits.",
			264,264,"Arguments of quantum discreteness or continuity are irrelevant-or not the point. Nor is it important that any (t) here present the nature of a photon or other boson accurately. For these are purely symbolic concepts. Indescription they do not act as they do as real objects. In fact, a real photon, while detectable and perceivable by other objects (instruments, atoms, etc) the detection is merely effectual. The precision of whatever symbolic quantity of whatever property is subject to the symbolic precision of the perceiver (in mathematics and physicality.)",
			265,265,"It is of no consequence in a fundamental way that there is a science of light or subatomic. Metas do not know the science of light but they do relate to light. Light relating to metal emits electrons. That relation is not knowledge. Yet light related totally to the metal.",
			266,266,"Knowledge is the relation of electronics and all other fundamental particles and all of the other *unknown* physical components in relation?? Knowledge is not to be found discretely... knowledge is a symbol reductional relating notions of utility. Utility being another symbolic relation of effects.",
			267,267,"Explanations become absurd. Absurd -> irreducible. Irreducible -> non computable. Irreducible -> non related. Non related -> infinite loop.",
			268,268,"Demarcation -> denote -> declare -> differentiation -> compute. Time is the measure is the medium of information of computation.",
			269,269,"To compute is to relate is to demarcate relation.",
			270,270,"IS is computation. IS is the computational relation.",
			271,271,"To IS takes time.",
			272,272,"To IS is to differentiate. IS is NOT is the difference and that difference is a symbolic state where IS(t.o) = IS(t.1) then (t.o)=(t.1). Instant. No Change. No difference.",
			273,273,"Learning is to notice difference.",
			274,274,"Learning is a symbolic reduction. Learning is labeling with inference -> a recursive contingent demarcation of This Is Not That...",
			275,275,"Type I and Type II errors and cognitive gias and all other concepts of pattern recognition, clustering, similarity, scoring, etc are demarcations of This Is Not That Is Not That... and at some point the recursion is terminated.",
			276,276,"Computation -> Demarcation -> Differentiation ==> saccade.",
			277,277,"Existence is saccade relation.",
			278,278,"The fundamental relation is saccadic. A computation. Its unit is a compute.",
			279,279,"A compute is a configuration.",
			280,280,"To compute is to re-configure.",
			281,281,"Time is the relation between symbolic configurations.",
			282,282,"Time is the distance between configurations.",
			283,283,"How different is one configuration from another configuration? Time... how many computes...",
			284,284,"The atomic unit of a compute does not exist. A compute is the atomic unit. From 1 to 0. That is a compute. TIme is defined as the difference between 1 and 0, a bit, a bit flip. It is 1. From . to __. From . to .. ........",
			285,285,"A compute is. It is physical. That is, existence becomes physical. The mere 1 is not 0 imbues all, It is non-physical or metaphysical. ONLY when there is No Differentiation. The One or The Non (those are the same in total isolation.)",
			286,286,"Any differentiation whatsoever is a compute. e.g. The millionth digit of pie to the millionth and 1 digit of pi is not even close the *smallest* notion of a compute.",
			287,287,"Compute all the way down and up.",
			288,288,"This is why time does not exist from the frame of reference of a photon. A photon does not compute by itself. A photon in relation -> computes.",
			289,289,"Time in computational complexity is analyzed without respect to clock time/physical time. This works because time is purely a metric of differentiation.",
			300,290,"When one says a computation will not complete or is non-computable that means the distance between [a]configuration is infinitely different from [b]configuration.",
			301,291,"One fundamental theory replaces another. This will continue indefinitely. Differentiation continues forever... until all is differentiated.",
			302,292,"The phenomena identified as fundamental: space, time, matter, logic/math -> differentiation - >computation.",
			303,293,"The human condition is not fundamental. Politics, society, civilization, currency, etc are not fundamental. The science of the human condition are symbolic. Representations.",
			304,294,"The sciences are required to explore all symbolic relations. Sciences and all other incomplete and incorrect models of all of existence are fundamental to all existence. Existing.",
			305,295,"What is the Right Model Is Not. There is only one model. One Model === Everything.",
			306,296,"These distinctions are necessary to reset the idea that all the theories, philosophies and sub models can ever be comprehensive.",
			307,297,"Few humans claim it matter to be comprehensive.",
			308,298,"{Claims, beliefs, ideas, lemmas, theories, science}->{symbolic relations between symbols, symbols relate in instruments}",
			309,299,"Would mathematics convince you? Do mathematics convince a planet to stay in orbit? Is a planet not also composed of its inhabitants? If not, how are the inhabitants not part of the planet?",
			309.9,300,"The inhabitants of earth are intelligent. No. They are differentiated slightly.",
			310,301,"Intelligence is a reductive symbolic relation usually referring to *self* - *awareness* self is not self validating. Awareness if finite.",
			311,302,"An Infinite Awareness cannot distinguish.",
			312,303,"Observable phenomenon need to be explained. The explanations are limited and barely fit the limited phenomenon.",
			313,304,"The prime numbers cannot be observed finitely. The prime numbers cannot be modeled finitely.",
			314,305,"The previous (t) is impossible unless the reader (a presumed) exists and has prior experience with the symbolics (and proofs) of number theory... which presumes the symbolics of logic and Peanos axioms.",
			315,306,"Axioms are agreed upon START POINT.",
			316,307,"Axioms are assumptive.",
			317,308,"The entire universe is without ASSUMPTION.",
			318,309,"IF. A mathematical description of any phenomenon is not sufficient for its explanation nor its creation.",
			319,310,"Progress is a local phenomena and an incomplete idea.",
			320,311,"Everything is conserved. COnservation of momentum... energy... information...",
			321,312,"The deepest quantum theories do not contain a full account of all that exists. They are not self explaining. The broader the theory goes the deeper the symbolics of symbolics get. The unaccounted for, the approximants is turned into An Object with The Missing Properties of The Theory.",
			322,313,"All theories are incomplete.",
			323,314,"Knowledge is not an object of reality.",
			324,315,"Explanations are not objects of reality.",
			325,316,"Knowledge, math, explanations, theories are relations between everything/anything.",
			326,317,"Relations... the quantity of relations are everything. They do not Explain everything they ARE everything.",
			327,318,"Out of The Multiple Ones arises Everything.",
			328,319,"Observed Time is not Time it is the differentiation of the One into the Multiple.",
			329,320,"The observations of patterns, laws, regularities, discreteness is determined.",
			330,321,"All irregularities and all regularities must exist in everything",
			331,322,"The very definition - real properties (relations) of regularities is why we observe them as we do.",
			332,323,"The creation of augmented, mixed and virtual realities will unveil the Everything. An Infinite virtual reality has long been evolving. More improbable virtual realities will be brief, as they will not have robust relations.",
			333,324,"It is not a matter of time. It is a matter computation. It is not a matter of matter. It is a matter of differentiation.",
			334,325,"That we do not observe various phenomena is not evidence those phenomena do not exist.",
			335,326,"Ideas, memes, prices, values, beliefs, stories, narratives are network effects. These are symbolics that measure network connectivity.",
			336,327,"Value is only possible through relation.",
			337,328,"A vehicle has no value if there is no network to move through. A person does not exist outside of a community. An organ is not without relation to other organs. on so on and so on on and on.",
			338,329,"{Marginal utility, rational man, intelligence, knowledge, ontology, existential, stochastic, catastrophe theory, set theory} the symbolic reductive traces of relation.",
			339,330,"The notions of incompleteness in math and the halting problem in computer science and complexity in biology and entropy in physics are all isomorphic symbolic representation of infinite relation.",
			33.99,331,"The duality cropping up everywhere is more than a duality - its a multiplicity. Nothing is One THing. The one 1 is not just a Single Thing.",
			400,332,"Set Theory is a very fundamental symbolic system. It is not the fundamental system. FOr itself relies on the notion of relation. Sets of things, even abstract, things implies relation -> a differentiation. The employ set... while empty of numeric things is not empty of relation. The paradoxical concept of the set of all sets being resolvable due to the empty set... the not set... is paradoxical only in a reduced relational model.",
			// 401,333,"One must admit everything. Everything exists. Not everything that can exist, exists. There is not impossibility. There are improbabilities. COnsider even in math... there are no impossible numbers. Sure one can define a prime that is also a compound. It simply does not add any new relation so we reduce it. Or what is a number divided by 0? We call it undefined but only with the context of the systems we use. That does not imply universally that something cannot be divided by zero. We merely need only differentiate... or put that notion in a relation. From propositional logic to first order to second order to in order to type theory... one theory on top of another in infinite regress up and down and all that remains is relation. And practically speaking the relations are either used/reused or unrelated. Deduction and INduction do not relate it all.",
			402,334,"Learning is relation. What is learned by an entity is relations between the entity and other entities - entities and other entities.",
			403,335,"Entities are robustly related symbolics. A person is related to other symbols with similarly robust person like relations.",
			404,336,"A Person now is related to a person then into a person by a name due to the similarities of relations of the now person and the then person.",
			405,337,"The difference between then-configuration and now-configuration is what we label time... space... spacetime.",
			406,338,"Time we attribute to differences unseen in 3d space. Space is what we attribute to seen changes.",
			407,339,"Space encomposses time because we notice space changes as accuring through time. We notice the space changes of our clocks. hands on faces, pendulums, atomic oscillations.",
			408,340,"The curvature of spacetime by mass is the result of relations. Massive objects have more relations -> more configurations -> more symbolic possibilities.",
			409,341,"Newtonian models of existence merely simplify relations. They cannot *handle* the relational complexity of full existence. But full existence has more and less robust relations and the less robust are so improbable over local sub_relational networks they do not disrupt common physics, math and belief systems.",
			410,342,"More information -> More relations destroys all models truth.",
			411,343,"Relational networks is everything. Distance is a generalized relational concept... how many relations between a symbolic relation and another. That distance is given many names: time/duration/cycles, space/length, meaning, temperature, hops/nodes, taste/tone/slow/harmony. This is the entire point.",
			412,344,"Cooking is a good example of relational distance. There is a large aesthetic difference between raw ingredients with relations and their final highly connected form. The relations cannot be shortcutted. There is no reductive process to relate raw ingredients in an exquisite meal without the relational configuration of cooking.",
			413,345,"All mathematics is an exposition of relation. Call this entire (t)-exercise... relation theory and now call it relational theory.",
			414,346,"This is not a theory. It is every theory. Part of everything connective like any theory.",
			415,347,"It is anti-theory. A permit of all theories.",
			416,348,"Robust through Relation - RTR - the probability of a relational structure showing up through reconfiguration.",
			417,349,"Art is a reconfiguration.",
			418,350,"Capitalism is a reductive ideal that has not shown RTR. Pure capitalism is only an idea. A very improbable configuration.",
			419,351,"Every philosophy and ideal and religion is a reductive justification for perceived connected configurations.",
			420,352,"No local, non-everything entity has relatively finite - limited -relational perception. Only partial truth, something, in relation is possible for limited subnetworks.",
			421,353,"Total connectivity is only possible through all reconfigurations.",
			422,354,"Most human reconfigurations (strategies, politics, theories) are not RTR. Most are reductive attempts at perceived progress. Improbabilities stumbling, exploiting, more improbabilities.",
			423,355,"These (t. 422) reconfigurations are improbable in the space of all configurations.",
			424,356,"If everything is, how are some configurations improbable?",
			425,357,"In everything, everything is probable equally.",
			426,358,"Yes. But the distance between improbable configurations is invariant.",
			427,359,"The past is improbable to reconfigure from the present.",
			428,360,"The present is not present.",
			429,361,"Future events... future re-configurations are no more probable than past ones.",
			430,362,"Probability is an effect of our limited subnetwork.",
			431,363,"All is equal probability.",
			432,364,"Certain sub-networks of sub-re-configurations are tuned improbable and probable to certain other reconfigurations.",
			433,365,"To a telescope in 1692 Kepler 452b is improbable -> impossible. The relational observation of the relational configuration of that telescope cannot relate to-cannot fathom-Kepler 452b - a planet too distant - too differently configured (in time and space).",
			434,366,"Configurations - relations of relations - networks - are a difficult concept. And to suggest space, time -> spacetime is the same .... is bold but the ultimate move.",
			435,367,"Why this master stroke now? and not then? not in the future?",
			436,368,"Irrelevant. Relevant only locally?",
			437,369,"Locally means_ refers only to a subnetwork.",
			438,370,"Language came before mathematical abstraction before ... is just a more ROBUST RELATION.",
			439,371,"Mathematics is not robust. It's language/process (its relations) do not relate many to many.",
			440,372,"Language-> robust and multi-relational connectors relate more to more.",
			441,373,"Then. Now. Future -> Experience. Experiencing. Likely to experience.",
			442,374,"Numeracy. Literacy. Punctuality. Local Human Ideas. L H I.",
			443,375,"A plant is illiterate, innumerate and does not show up at anytime.",
			444,376,"But it relates -> responds in cycles. more or less perfectly.",
			445,377,"Cycles are simply reconfigurations similarly. They are relations related closely.",
			446,378,"Patterns -> related relations.",
			447,379,"*Strange* Loops of recursion. Self. Self awareness.",
			448,380,"The only possibility of *self* awareness is related relations relating. *Noticing* relatedness.",
			449,381,"It is circular.",
			450,382,"The circle is the point.",
			451,383,"A circle is a point.",
			452,384,"Dimensionality is a local phenomena observed by limited subnetworks.",
			453,385,"Humans will observe and theorize endlessly.",
			454,386,"Until their end. When non-human networks no longer call human networks human. And human networks no longer call humans humans. Relations break. Relations no more.",
			455,387,"When is not. When is a point in distance.",
			456,388,"Distance is the unreasonable effectiveness of mathematics.",
			457,389,"No matter our differentiation we end up numbering. One successor from another.",
			458,390,"How many?",
			459,391,"Many is the fundamental differentiator.",
			460,392,"How many what? what is the what?",
			461,393,"What always reduces to a measure.",
			462,394,"Measures are traces of relations.",
			463,395,"A full theory of everything is an enumeration of all relations.",
			464,396,"Engineering is just theorizing.",
			465,397,"Engineered theories are more trusted.",
			466,398,"They aren't truth. Apparently more Robust Through Relation. The relation of *physical objects* to other *physical* *objects*",
			467,399,"And then/now/soon virtual engineering. New relations trusted in new physics. But not true. Just trusted - just related in relation.",
			468,400,"This is psychology.",
			469,401,"Minds are virtual reality. Isomorphic. In-complete.",
			470,402,"Every human lives in a reductive relation of relations - a virtual reality.",
			471,403,"Analyzing each virtual reality is psychology.",
			472,404,"Analysing the *physical* relations versus the verbal relations is behaviorism.",
			473,405,"The brain relates.",
			474,406,"The brain relates to itself. To the body. To the world.",
			475,407,"It represents itself.",
			476,408,"The Brain. It Is Not.",
			477,409,"The mind is not. The brain is not. The body is not.",
			478,410,"All are reductions of reductive networks in *constant* ... relating re-relating.",
			479,411,"That computation is fundamental is not surprising. Now -> within this relational framework.",
			480,412,"To compute is to relate.",
			481,413,"A relation -> an atomic relation is a Compute. A computation.",
			482,414,"All economic value for humans_human_machines will be related to relating.",
			483,415,"Relating is data.",
			484,416,"Data is traces of relations.",
			485,417,"Data is.",
			486,418,"Relation Is.",
			487,419,"Only the entire network. The everything can relate. All to all. The universe... the multiverse... the universe of universes.",
			488,420,"Sub-relations-of-relations -> networks transcode data. They do not do. There is no activity. Motion is an illusion. Except... as reductive concept.",
			489,421,"What's the point?",
			490,422,"Asking for a point is a relation reduction.",
			491,423,"Asking for *what use* is a relation reduction. - what use does a fly have for the Large Hadron Collider? Some? None? Maybe?",
			492,424,"Use is relational.",
			493,425,"It will continue to be found _ _ _ other configurations _ _ _ of the world we contemplate use utility complexity computation more and more relational.",
			494,426,"Am I thinking any of these (t's)?",
			495,427,"No.",
			495.1,428,"Go to (t496)",
			495.2,429,"INTERJECTION: the standard model is not. reality. - management",
			495.3,430,"Every philosophy book is about: Love. heart???",
			495.4,431,"Nothing Loves Nothing and Everything.",
			495.5,432,"There is No: There is no Grand Theory. There is no AI. The Singularity is a small idea... it's a local myth.",
			496,433,"Love admits all relations",
			497,434,"Love is not true, but is robust.",
			498,435,"Love is the symbolic relations between anything.",
			499,436,"Love is pure symbol.",
			500,437,"symbol.",

		      ];